### ISSUE TITLE
illegal MM syntax errors

### ISSUE THREAD

**Issue by OrbitalManeuvers** [dangaffa/DunaDirectRedux#1]
MD-RealPlume.cfg has 3 MM syntax errors, all the same:

@PART[MD-Stage2Engines]:NEEDS[RealPlume,SmokeScreen, !Waterfall]

Space before "!Waterfall" is illegal.

p.s. thanks for working on this mod!

**Comment by dangaffa** [comment]
Just fixed in V1.01
